### ISSUE TITLE
Issue when adding inline style on <Treebeard /> root

### ISSUE THREAD

**Issue by mjw56** [storybooks/react-treebeard#103]
Hi, thanks for this project! I am integrating it into an app running React 16 and quickly ran into this issue when adding an inline `style` tag onto the `<Treebeard />` react element.

I need to dig some more, but would be happy to fix and PR.

![image](https://user-images.githubusercontent.com/161528/31590241-ed1553d4-b1da-11e7-8dc0-8015572370ce.png)

**Comment by bindalkumar** [comment]
style key value must be an valid JSON object. Please create your own style as per given format. Please refer:

```
https://github.com/alexcurtis/react-treebeard/blob/master/src/themes/default.js
```
