### ISSUE TITLE
animations={false} prevent the right arrow from changing to a down arrow

### ISSUE THREAD

**Issue by franckl** [storybooks/react-treebeard#111]
With animations={false} the arrow icon is not moving down. Is it easy to fix ?
![react-tree-bug](https://user-images.githubusercontent.com/3875803/34322146-da4e389e-e81f-11e7-80e1-6afdd1cd6e0f.gif)

**Comment by maximilianoforlenza** [comment]
fixed https://github.com/storybooks/react-treebeard/pull/174
