### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by therealparmesh** [storybooks/react-treebeard#117]
I'm wondering if this project is still alive or not. This is a high-quality React component that needs updating. Thank you!

**Comment by MichaelDeBoey** [comment]
@therealparmesh This project unfortunately isn't really maintained yet...
I hoped to help @alexcurtis maintain the repo, but I'm short in time myself.
If you want to help contribute/maintain the repo that would be nice! 🙂

**Comment by therealparmesh** [comment]
I’m definitely interested. The potential for this project is that it’s the best overall React tree component. And I’d be able to make some time for it. The only thing I’d really desire is a roadmap or at least a real discussion about one.

**Comment by MichaelDeBoey** [comment]
@therealparmesh You can defo start a new thread about discussing the roadmap 🙂

**Comment by therealparmesh** [comment]
@MichaelDeBoey I’ll go ahead and do that. Hopefully I can join you as a project maintainer soon!

**Comment by xgqfrms-gildata** [comment]
Has any process achieved?

**Comment by ndelangen** [comment]
First truly appreciate the work and energy put into this ❤️ 

We use this component over at Storybook, and needed this to get updated.

I have a fork that has migrated all styling to use emotion from radium.
Does it make sense to open a PR here? There is a long list PRs, so I'm hesitant to open a PR and just wait. What's the right path to take here to get some changes in?

Can we open this repo up to all potential maintainers maybe? See who wants it?

I hope I'm don't come across as negative or unappreciated or demanding, absolutely not my intention.

@MichaelDeBoey @alexcurtis @therealparmesh

**Comment by alexcurtis** [comment]
@ndelangen I have added you as a maintainer. I welcome any help as I just don't have the time myself. Many thanks!

**Comment by ndelangen** [comment]
Thanks @alexcurtis can you give me rights to publish to npm too?

Let me know if you want to have a personal chat to establish trust first.

**Comment by ndelangen** [comment]
@alexcurtis I'd like to move this repo to the storybook organisation, so all storybook maintainers have instant access too, how do you feel about that?

**Comment by alexcurtis** [comment]
@ndelangen I would be ok with that. I think it would be better maintained in the storybook org. Let me know if you need anything from me to achieve this.

**Comment by ndelangen** [comment]
Yes I do, I'll add you as a temp member of the storybook org, and then you can initiate the transfer.

**Comment by ndelangen** [comment]
Can you please add me as owner in npm too?

my npm name is `ndelangen`
