### ISSUE TITLE
how to use container decorator ? 

### ISSUE THREAD

**Issue by radjivF** [storybooks/react-treebeard#122]
I have no clue what to put in the props, any help ?

**Comment by Jongkeun** [comment]
Hi @MichaelDeBoey, I agree with @radjivF .
I use this project as library.

But the example is too difficult to use.
If this project is not died, please let us the easy way to use decorators.
Please tell me how the same results come out as an example by using only decorators.
like this:

```
const decorators = { ... };

<Treebeard
    data={this.state.tData}
    onToggle={this.onToggle}
    decorators={decorators}
/>
```

**Comment by Jongkeun** [comment]
@wuweiweiwu 
Could you let me know how to use it? Please.
I didn't know how to use `decorator`.
Even I saw the example code but that was imported the original code.
Do I have to import whole code of this repository, if I wanna use `decorator`?

**Comment by wuweiweiwu** [comment]
hi @Jongkeun do you mean [this](https://github.com/storybooks/react-treebeard#decorators)?

Decorators lets you specify your own loading, header, footer, etc components, the default is provided if you don't specify the prop (no action needed on your part) but if you do want to customize those components you'll have to specify a `decorator` prop

**Comment by wuweiweiwu** [comment]
You do not have to import the whole code of the repository, hope that helps!

**Comment by Jongkeun** [comment]
@wuweiweiwu
Thanks. I am going to try.

**Comment by codecoffemusic** [comment]
@Jongkeun Did you figure this out yet ?

**Comment by Jongkeun** [comment]
@codecoffemusic Sorry I'm late.
And nope. I gave up :(
