### ISSUE TITLE
Online example dead

### ISSUE THREAD

**Issue by FabianPiconeDev** [storybooks/react-treebeard#131]
Your online example does not work. 404 page. http://alexcurtis.github.io/react-treebeard/

**Comment by MichaelDeBoey** [comment]
The demo URL is now http://storybooks.github.io/react-treebeard (see #132)

**Comment by veksen** [comment]
The project description is still linking to the old URL:

![image](https://user-images.githubusercontent.com/3461986/44491818-66e93280-a630-11e8-9243-74b4eab03094.png)

**Comment by FabianPiconeDev** [comment]
Fixed in https://github.com/storybooks/react-treebeard/pull/132.

**Comment by mismith** [comment]
the new URL is now dead too :(

**Comment by maximilianoforlenza** [comment]
@mismith http://storybookjs.github.io/react-treebeard/

**Comment by mismith** [comment]
Ah, thanks! The docs still link to
http://storybooks.github.io/react-treebeard/ from "Here" in the readme, as
well as the repo link in GitHub. Also, looks like the build status badge is
a broken image, too.
