### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by wuweiweiwu** [storybooks/react-treebeard#133]
A lot of dependencies are out of date.

especially `react` and `react-dom` which are on 15.x

We should be at least on 16.x

And `prop-types` are its own package now.

**Comment by szaudowsky** [comment]
what about this PR? You gonna merge it in few days?

**Comment by maximilianoforlenza** [comment]
@wuweiweiwu @szaudowsky I will upgrade dependencies

**Comment by maximilianoforlenza** [comment]
done https://github.com/storybooks/react-treebeard/pull/168
