### ISSUE TITLE
How to update the tree with the data from the API

### ISSUE THREAD

**Issue by vinayqv** [storybooks/react-treebeard#139]
How to update the react treebeard tree with the data from the API??

**Comment by Shyroby** [comment]
In `componentDidMount()` lifecycle method you can fetch your api data:

`
  componentDidMount() {
    fetch('https://api.mydomain.com')
      .then(response => response.json())
      .then(data => this.setState({ data }));
  } `

**Comment by vickyvishal** [comment]
How to add API data to the tree on click of the node? i.e On click of a node I am fetching data, how can I insert it after the API promise is resolved?

**Comment by maximilianoforlenza** [comment]
Hi @vickyvishal @vinayqv I use react-redux and when press onToggle button I dispatch action to fetch new data. Eg
```
 onToggle(node, toggled) {
        const {cursor, data} = this.state;

        if (cursor && !includes(cursor.children, node)) {
            cursor.toggled = false;
        }

        assign(node, {toggled});

        if (node.children) {
            assign(node, {toggled});
        }

        if (cursor && !cursor.children && node.children) {
            cursorSide.toggled = false;
        }

        if (node.side) {
            this.props.fetchSurvey(node._id);
        }

        this.setState(() => ({
            cursor: node,
            data: assign({}, data)
        }));
    }
```
