### ISSUE TITLE
crashings with large json data

### ISSUE THREAD

**Issue by kfirsuperquery** [storybooks/react-treebeard#141]
app is crashing when passing big json data.
is there any way to fix it ? what should i do ?
please help.

**Comment by mmartinson** [comment]
Could you provide some more details to reproduce? What does the crash look like? How big is the JSON data? Can you determine at what size it breaks by truncating the data to a certain length/depth? Can you confirm that different test data of the same size breaks the same way?

**Comment by maximilianoforlenza** [comment]
@kfirsuperquery can you give me an example please?

**Comment by maximilianoforlenza** [comment]
@kfirsuperquery please reopen when you can send an example.

Thanks.
