### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by mmartinson** [storybooks/react-treebeard#143]
Hi @alexcurtis and other maintainers. 

I'm just checking in to see if you are interested in staying on as the maintainer of this project, if you'd like to loop in some of the community to help, or if your preference is to avoid much change and keep the project as-is.

It seems as though there are a number of long running issues and PRs that could get moved through. Totally understand if you're busy and couldn't be bothered, but it would be good to have a path moving forward or those wanting to use and improve this further.

To people with open PRs? Is anyone interested in taking on maintenance? Are there any active forks?

**Comment by maximilianoforlenza** [comment]
Hi @mmartinson I new maintainer for this project, if you want to colaborate tomorrow i create new issues to do.

**Comment by mmartinson** [comment]
I've moved on to [something custom](https://github.com/CodeCastTeam/functional-file-tree) for my use case won't have capacity for maintaining this. Good luck!
