### ISSUE TITLE
colors won't change no matter what i do

### ISSUE THREAD

**Issue by adamscottv** [storybooks/react-treebeard#145]
Hi,

My app doesn't have a black background, so was trying to do a simple thing like change the background color to white and font color to black. I can apply styles using the method in the styles.js example, such as adding padding, and it works. But adding backgroundColor or color has no effect. Also tried directly modifying default.js to no effect. Seems like either of these approaches should have worked.

Please help, I really want to use this component, not sure what is going on. I cleared browser cache, so caching isn't the issue. 

Thanks.

**Comment by Kaylen-Pillay** [comment]
@adamscottv did you manage to fix this?

**Comment by VMahipalReddy** [comment]
Any solution ?? @adamscottv

**Comment by maximilianoforlenza** [comment]
https://github.com/storybooks/react-treebeard/pull/171
