### ISSUE TITLE
TypeError: "CSS2Properties doesn't have an indexed property setter for '0'"

### ISSUE THREAD

**Issue by adiguent** [storybooks/react-treebeard#148]
I an trying to use your example befor starting to modify anything.
but I'm facing this error : TypeError: "CSS2Properties doesn't have an indexed property setter for '0'".
Could any one help me?

**Comment by Luxapodular** [comment]
+1 I'm having the same issue. 

I've used create-react-app... Not sure if this will help.

**Comment by christopher-johnson** [comment]
please disregard the above commit as the solution.  For me, the error (which is fatal) only occurs in Firefox.

I resolved the problem by overriding the default styles for the [`activeLink` and `link`](https://github.com/storybooks/react-treebeard/blob/master/src/themes/default.js#L18-L26)  elements, which are referenced in the decorators code in [`style.container`](https://github.com/storybooks/react-treebeard/blob/master/src/components/decorators.js#L64) which does not exist in the default styles.  By adding the container style element in the node object like this:
```
tree: {
    node: {
       container: {
                link: {
                  cursor: 'pointer', position: 'relative', padding: '0px 5px', display: 'block'
                },
                activeLink: {
                  background: '#31363F'
                }
        }, ...
```
the error goes away, and Firefox works.

**Comment by neihcnim** [comment]
I added the container style element but the problem persists. @christopher-johnson , was there any other changes you did to fix the issue? Thanks.

**Comment by christopher-johnson** [comment]
yes.  I also am overriding the default Container decorator, so you can just copy the [source](https://github.com/storybooks/react-treebeard/blob/master/src/components/decorators.js), and add local modifications.  Then reference this file with the decorators prop as described in the docs.  See [here](https://github.com/ubl-chj/collections-ui/blob/master/packages/manifest-viewer/src/components/ui/controls/ContentTreeDecorators.tsx#L54-L56) for an example:

**Comment by tahv0** [comment]
I'm having this issue with version 3.1.0 on Firefox. Is there a fix coming?

**Comment by neihcnim** [comment]
> I'm having this issue with version 3.1.0 on Firefox. Is there a fix coming?

Use the workaround at https://github.com/storybooks/react-treebeard/issues/148#issuecomment-433347121 which garnered some thumbs up. Worked for me.

**Comment by ancilt26** [comment]
Thanks @christopher-johnson ! 🙏🏽

Here's the TLDR version: 

Override the `styles` prop of the `Treebeard` component as shown below 

```javascript
        <Treebeard
          data={data}
          onToggle={this.onToggle}
          style={{
            tree: {
              base: {
                listStyle: 'none',
                margin: 0,
                padding: 0
              },
              node: {
                container: {
                  link: {
                    cursor: 'pointer',
                    position: 'relative',
                    padding: '0px 5px',
                    display: 'block'
                  },
                  activeLink: {
                    background: '#31363F'
                  }
                },
                link: {
                  cursor: 'pointer',
                  position: 'relative',
                  padding: '0px 5px',
                  display: 'block'
                },
                activeLink: {
                  background: '#31363F'
                },
                toggle: {
                  base: {
                    position: 'relative',
                    display: 'inline-block',
                    verticalAlign: 'top',
                    marginLeft: '-5px',
                    height: '24px',
                    width: '24px'
                  },
                  wrapper: {
                    position: 'absolute',
                    top: '50%',
                    left: '50%',
                    margin: '-7px 0 0 -7px',
                    height: '14px'
                  },
                  height: 14,
                  width: 14,
                  arrow: {
                    fill: '#9DA5AB',
                    strokeWidth: 0
                  }
                },
                header: {
                  base: {
                    display: 'inline-block',
                    verticalAlign: 'top'
                  },
                  connector: {
                    width: '2px',
                    height: '12px',
                    borderLeft: 'solid 2px black',
                    borderBottom: 'solid 2px black',
                    position: 'absolute',
                    top: '0px',
                    left: '-21px'
                  },
                  title: {
                    lineHeight: '24px',
                    verticalAlign: 'middle'
                  }
                },
                subtree: {
                  listStyle: 'none',
                  paddingLeft: '19px'
                },
                loading: {
                  color: '#E2C089'
                }
              }
            }
          }}
        />
`

**Comment by maximilianoforlenza** [comment]
Fix https://github.com/storybooks/react-treebeard/pull/147

**Comment by jtorres2121** [comment]
I'm still seeing this issue even after updating the npm package to include fix #147.  
Is there anything else that I need to do to make this work on FireFox?

**Comment by jtorres2121** [comment]
I made this work by overriding the style prop, as suggested by ancilt26 (thank you!)
My impression was that it should work without overriding the style prop, after maximilianoforlenza's fix, but it does not.  
Are there plans to fix this without having to override the style prop?

**Comment by maximilianoforlenza** [comment]
Hi @jtorres2121 what version are you using?

**Comment by jtorres2121** [comment]
Hi Max,
I have 3.1.0.  I updated the npm package 8 days ago, I should have your changes.

**Comment by maximilianoforlenza** [comment]
No, because the fix was after publish v3.1.0. I haven't  access to do a publish. I'll have this on Wednesday. @jtorres2121

**Comment by maximilianoforlenza** [comment]
Hi @jtorres2121 please try it v3.2.0 should be fixed.

**Comment by oktorakevinarigi** [comment]
After I debug I found the problem here.
![image](https://user-images.githubusercontent.com/10071226/56874859-f7510000-6a66-11e9-8fde-e234a97c2a1a.png)

And I deleted the following coding and all the way smoothly,
![image](https://user-images.githubusercontent.com/10071226/56874892-3da65f00-6a67-11e9-97a0-8b1c5be6afac.png)

**Comment by maximilianoforlenza** [comment]
@oktorakevinarigi Are you using chorme v74?

**Comment by oktorakevinarigi** [comment]
@maximilianoforlenza yes i use chrome 74

**Comment by maximilianoforlenza** [comment]
@oktorakevinarigi and what react-treebeard version are you using?

**Comment by oktorakevinarigi** [comment]
@maximilianoforlenza I don't use react-treebeard
