### ISSUE TITLE
node: link styles no longer applied.

### ISSUE THREAD

**Issue by emiliano-ponce** [storybooks/react-treebeard#149]
Upgraded from v2.1.0 to v3.1.0

Default styling is not applied and if you supply custom styles it is not applied either.

**Comment by maximilianoforlenza** [comment]
@emiliano-ponce @ticholNyler fix v3.2.0 https://github.com/storybooks/react-treebeard/releases/tag/v3.2.0

Here is codesanbox with the example https://codesandbox.io/s/93720rv5p4
