### ISSUE TITLE
Link styles are not used 3.1.0

### ISSUE THREAD

**Issue by mouradmourafiq** [storybooks/react-treebeard#152]
It seems that the example is not working on 3.1.0 version.

Just as a suggestion, it would be more useful and would require less documentation if the library is using class names.

**Comment by ticholNyler** [comment]
Really need to have active styling working. No fix yet?

**Comment by bwobst** [comment]
Confirmed link styles do not work in 3.1.0. Rolling back to 2.1.0 works.

**Comment by maximilianoforlenza** [comment]
Hi @mouradmourafiq @ticholNyler @bwobst please try it in the new version (3.2.0)

**Comment by maximilianoforlenza** [comment]
Hi @bwobst , please try it on version 3.2.0
