### ISSUE TITLE
How to search by both name and description

### ISSUE THREAD

**Issue by january2019** [storybooks/react-treebeard#153]
Hi,
I am learning React and trying to implement this treebeard. I have modified data.js file a little bit and added  a property description like below for all parent and children

> name: 'react-treebeard \n',
    description: 'xyz',
    toggled: true,

I am trying to implement search functionality for both name and description, I mean even if input 
 matches description I want to expand the tree. Any help or suggestions please how can I do that?

**Comment by january2019** [comment]
I have figured it. Thank you

**Comment by joseph-vedadi** [comment]
Would it be too difficult to share how you did it ?
