### ISSUE TITLE
efficient? fast? 

### ISSUE THREAD

**Issue by Introvertuous** [storybooks/react-treebeard#154]

**Comment by MetaFight** [comment]
I would agree, but it might be more productive to suggest a fix, or provide a PR.  As it stands this is just a rant.

**Comment by Introvertuous** [comment]
@MetaFight a rant? that was barely a jab. Also to your other point, I would rather not spend my time working with a collaborator who plasters false adjectives all over their library in an attempt to gain stars, which I suppose is essentially analogous to karma on reddit, or at least equally irrelevant.
