### ISSUE TITLE
activelink style not working

### ISSUE THREAD

**Issue by ribhu0405** [storybooks/react-treebeard#160]
Active Link property is not working . I have applied below code in styles.js file , it was working with previous versions.

node: {
            activeLink: {
                background: '#20a8d8',
                color: '#ffffff'
         }
}

**Comment by ponyczek** [comment]
Same problem here.

**Comment by NateRadebaugh** [comment]
The only code explicitly related to `active` prop is in `header.js` (eg `NodeHeader`):

```jsx
  const container = [style.link, active ? style.activeLink : null];
  const headerStyles = Object.assign({container}, style);
```

This doesn't seem like it's doing what the code expects... since we end up with the following value for `headerStyles`:

```jsx
const container = [style.link, active ? style.activeLink : null];
                             // = [{link: true}, true ? {activeLink: true} : null]
                             // = [ { link: true}, {activeLink: true} ]

const headerStyles = Object.assign({ container }, style);
                             // = Object.assign({ container }, { otherStyle: true})
                             // = { container: [ { link: true}, {activeLink: true} ], otherStyle: true }
```

So we end up with `{ container: [ { link: true}, {activeLink: true} ], otherStyle: true }` when we want something like `{ link: true, activeLink: true, otherStyle: true }`

**Comment by NateRadebaugh** [comment]
Another update: the decorator expects a `style.container` and also a `style.header` attribute
```jsx
class Container extends React.Component {
    render() {
        const {style, decorators, terminal, onClick, node} = this.props;

        return (
            <div onClick={onClick}
                 ref={ref => this.clickableRef = ref}
                 style={style.container}>
                {!terminal ? this.renderToggle() : null}

                <decorators.Header node={node}
                                   style={style.header}/>
            </div>
        );
    }
```

**Comment by v0lkan** [comment]
Having the same issue.

As an interim solution, I defined a decorator like this:


```
import { Treebeard, decorators } from 'react-treebeard';

decorators.Header = ({ node, style }: any) => {
  const newBaseStyle = { ...style.base };

  if (node.active) {
    newBaseStyle.backgroundColor = '#ff0000';
  }

  return (
    <div style={newBaseStyle}>
      <div style={style.title}>{node.name}</div>
    </div>
  );
};
```

You only have to define it once before using the component, and can use any custom css inside the `if (node.active)` block.

The original TreeBeard decorated was using emotion styled components, but for some reason it clashed with my webpack setup; so used regular `div`s instead.

It doesn’t seem to have any observable impact on how the component functions, as far as I can tell.

Hope that helps y’all, until this issue is fixed.

**Comment by maximilianoforlenza** [comment]
Hi @ribhu0405, @ponyczek, @NateRadebaugh and @v0lkan . It's working for me.
```
 <Treebeard
                    {...props}
                    style={{
                        tree: {
                            base: {backgroundColor: 'white'},
                            node: {
                                activeLink: {color: 'brown', background: 'yellow'}
                            }
                        }
                    }}
                />
```
When toggle is open I set `node.active: true`

**Comment by NateRadebaugh** [comment]
@maximilianoforlenza can you provide a working codesandbox link?

When I try, the `style` tag requires everything in the `default.js` theme or it will throw an error. Then, if I override the `activeLink`, it does nothing: https://codesandbox.io/s/l28xqqqzzq?fontsize=14

**Comment by maximilianoforlenza** [comment]
@NateRadebaugh On codesanbox can you try point to master? Because react-treebeard 3.1.0 is old and has bugs

**Comment by NateRadebaugh** [comment]
I'm confused, `3.1.0` is the latest documented release: https://github.com/storybooks/react-treebeard/releases

Switching to point to `2.1.0` resolves the issue.

**Comment by maximilianoforlenza** [comment]
After v3.1.0 this bug is fixed

**Comment by maximilianoforlenza** [comment]
Hi @NateRadebaugh please try it on version 3.2.0

**Comment by maximilianoforlenza** [comment]
Hi @NateRadebaugh please try it on version 3.2.0

**Comment by NateRadebaugh** [comment]
Thanks @maximilianoforlenza I've verified this is now working with the latest code.
