### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by maximilianoforlenza** [storybooks/react-treebeard#167]
@pksunkara what is the status of the project? i might continue with this project refactoring some parts of code and merge PRs if you want.

**Comment by pksunkara** [comment]
Go ahead. I only did some stuff to get a basic release

**Comment by maximilianoforlenza** [comment]
Can you give me maintainer permissions? You have some PRs with fix eg: https://github.com/storybooks/react-treebeard/pull/147

**Comment by pksunkara** [comment]
Done. You probably would want to fix the tests first.
