### ISSUE TITLE
how to add node to children node?

### ISSUE THREAD

**Issue by zahrahajilary** [storybooks/react-treebeard#187]
hi , thanks for your repo ,
i wanna add some node dynamically in n levels  with fetching from api , how can i do it?
thanks for your helping .

**Comment by maximilianoforlenza** [comment]
Hi @zahrahajilary I think you should add node children when press on toggle button but can you show me your code?

**Comment by zahrahajilary** [comment]
i know it but there isnt any document how to do it . 
i should add new node to state , because the component render from state 
`
    onToggle(node, toggled){
        if(this.state.cursor){this.state.cursor.active = false;}
        node.active = true;
        const apiChild = `url`
        if(node.active) {
                DOCHTTP.get(apiChild)
                .then(res=>{
                    var dataChild = res.data.detail
                    console.log(dataChild)
                    dataChild.forEach(element=>{
                        var detailChild = {
                            id: element.pid,
                            name: `${element.title} - ${element.entityTypeName}`
                        }
                        node = {...node,children:detailChild}
                        console.log(node)   
                    }) 
                    
                })
                .catch(err=>{console.log(err)})
        }
        if(node.children)
        { node.toggled = toggled  
            this.setState({ cursor: node });
         }
 
    }
`
could you please take a example how to do it :( actually im a newer in React

**Comment by maximilianoforlenza** [comment]
@zahrahajilary I change forEach to map, please try it:
```
 onToggle(node, toggled) {
    if (this.state.cursor) {
      this.state.cursor.active = false;
    }
    node.active = true;
    const apiChild = `url`;
    if (node.active) {
      DOCHTTP.get(apiChild)
        .then(res => {
          var dataChild = res.data.detail;
          node = {
            ...node,
            children: dataChild.map(element => ({
              id: element.pid,
              name: `${element.title} - ${element.entityTypeName}`
            }))
          };
        })
        .catch(err => console.log(err));
    }
    if (node.children) {
      node.toggled = toggled;
      this.setState({ cursor: node });
    }
  }
```

**Comment by maximilianoforlenza** [comment]
The problem is you doesn't change the data. Change the node but no the original data.

I recommend move 
```
 DOCHTTP.get(apiChild)
                .then(res=>{
                    var dataChild = res.data.detail
                    console.log(dataChild)
                    dataChild.forEach(element=>{
                        var detailChild = {
                            id: element.pid,
                            name: `${element.title} - ${element.entityTypeName}`
                        }
                        node = {...node,children:detailChild}
                        console.log(node)   
                    }) 
                    
                })
                .catch(err=>{console.log(err)})
``` to new service or if you use `redux` move to redux and return data changed.
