### ISSUE TITLE
Issue with Chrome Version 74.0.3729.108 (64 bit)

### ISSUE THREAD

**Issue by matteoPhre** [storybooks/react-treebeard#193]
Hi, i've updated Chrome to new version and now this error appears:
`Uncaught TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported`.

My component is like:
`<Treebeard data={data} onToggle={this.onToggle} style={Style} />`
and Style is defined as docs.

Any suggestions? Thanks in advance

**Comment by maximilianoforlenza** [comment]
Hi @matteoPhre i'll plublish new treebeard version with the fix

**Comment by matteoPhre** [comment]
Great! I await release then, thank you!

**Comment by maximilianoforlenza** [comment]
@matteoPhre I release v3.2.1 with the fix https://github.com/storybooks/react-treebeard/releases/tag/v3.2.1

**Comment by maximilianoforlenza** [comment]
@matteoPhre I release v3.2.2 can you try this? thanks!

**Comment by matteoPhre** [comment]
Now it works again! Thank you! :)
