### ISSUE TITLE
How to theme/style tree base

### ISSUE THREAD

**Issue by madmunky** [storybooks/react-treebeard#213]
Can someone please post an example on how to theme or override the style on the tree base and other components.

I can update the header render for the tree items but not the actual tree base and things like the arrow animation.

**Comment by madmunky** [comment]
Perfect thanks, would be nice if the documentation was a little clearer but this works perfectly.

**Comment by maximilianoforlenza** [comment]
I agree

**Comment by madmunky** [comment]
Do you know if it's possible to do alternative line styles like

 li:nth-child(even) {
        background-color: black;
        color: white;
    }

    li:nth-child(odd) {
        background-color: #0000335f;
    }

**Comment by maximilianoforlenza** [comment]
I don't think so, because the style isn't in the node. Maybe you should set the style in the state of the component and change it dynamically

**Comment by heijntje** [comment]
Hi @maximilianoforlenza , I just came across this question and saw your example code, I see that you are setting the color for an active link to brown. But the color does not change when it is active, which is the exact problem I have and  why I came across this question.

Do you know if there is a way to set the color of an active link?
