### ISSUE TITLE
Memory leak in tweensContainer

### ISSUE THREAD

**Issue by eyala-stratoscale** [storybooks/react-treebeard#23]
There seems to be a memory leak here. I think its originating from velocity-react but still haven't figured out how it is caused. 

If you go to your demo and check for detached nodes you will see this number keeps rising and is not cleaned up.

**Comment by alexcurtis** [comment]
@eyala-stratoscale Thanks. I'll check this out today. It might be as easy as updating the dependency.

**Comment by eyala-stratoscale** [comment]
@alexcurtis , I tried bumping react-velocity version to their latest , 1.1.2 I didn't see any improvement there

**Comment by eyala-stratoscale** [comment]
Hey @alexcurtis  any updates regarding the memory leak ?

**Comment by MichaelDeBoey** [comment]
@eyala-stratoscale Is this one still present in [`v2.0.3`](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.3)?
