### ISSUE TITLE
Close one branch when other branch opened

### ISSUE THREAD

**Issue by ghost** [storybooks/react-treebeard#25]
I've been trying to tweak this so when you open a new branch, the previously opened branch closes, but I can't get it to work. Would really appreciate if this could be done. Thanks.

**Comment by popasquat89** [comment]
Just do something like this:

`function closeBranches(nodes){
    for(let i = 0; i < nodes.length; i++){
        const node = nodes[i];

        if(node.children && node.children.length){
            closeBranches(node.children);
        }

        if(node.toggled){
            node.toggled = false;
        }
    }
}`

You could also just set the current "cursor" field toggled, which you see in examples, to false before you set new cursor.
