### ISSUE TITLE
not built with external React

### ISSUE THREAD

**Issue by atZhengda** [storybooks/react-treebeard#41]
having a project which uses office react.min.js externally. While trying to include this component, npm downloads react anyway and hence multiple version of react is loaded. Is there a way to get around with this?
Thank you

**Comment by veeramarni** [comment]
I'm getting the same issue when using external React using webpack.

**Comment by alexcurtis** [comment]
ill look into extracting the example dependencies into another package.json. This will solve this. I'll get this done as soon as I can...
