### ISSUE TITLE
Collapse / Expand not working

### ISSUE THREAD

**Issue by mnboos** [storybooks/react-treebeard#58]
Hi alexcurtis
I've the the same problem as in issue #27 
The tree is shown correctly on initial render but clicking nodes does nothing - can't expand/collapse, active node not highlighted.

**Comment by sonuj** [comment]
expand and collapse of parent node is not working

**Comment by emilyfeder** [comment]
I think it's because React is not registering it as a state change and is not calling render() again. 
Also, I think ideally onToggle should switch the node toggled state internally inside the Treebeard Component instead of you having to manually do it each time.
Try the following instead (I haven't actually tested this, as a fair warning):

`
class TreeExample extends React.Component {
	constructor(props){
		super(props);
		this.state = {
			data: props.data
		};
		this.onToggle = this.onToggle.bind(this);
	}
	onToggle(node, toggled){
		if(this.state.cursor){this.state.cursor.active = false;}
		node.active = true;
		let new_data = this.state.data;
		if(node.children){
			node.toggled = toggled;
			new_data = Object.assign({}, this.state.data);
		}
		this.setState({ cursor: node, data: new_data });
	}
	render(){
		return (
			<Treebeard
				data={this.state.data}
				onToggle={this.onToggle}
			/>
		);
	}
}
`

**Comment by skohub** [comment]
Possibly you have put 
```
const data = {
    name: 'root',
    ...
}
```
inside **render** method, so the **data** is being rewritten from scratch on every click.

**Comment by kerams** [comment]
@skohub What do you mean by that?

**Comment by Waize** [comment]
There is an issue with the animations. 
If you turn them off:
`<Treebeard data={data} onToggle={this.onToggle} animation={false}/>`
It works fine. 
Maybe @MichaelDeBoey needs to double check the animation conditions in renderChildren from node.js

**Comment by Waize** [comment]
#111

**Comment by Waize** [comment]
@maximilianoforlenza with #174 this issue is worse than before: 
when `animation == false` it will not toggle at all. 
removing animations-flag will still not bring animations back.

**Comment by Waize** [comment]
@maximilianoforlenza any news on this?

**Comment by maximilianoforlenza** [comment]
No yet. I'll working on this today.

**Comment by maximilianoforlenza** [comment]
@Waize please try this https://github.com/storybooks/react-treebeard/issues/209

**Comment by Waize** [comment]
Woah ... I missed that you did a breaking change with forcing react >= 16.7.0. 
We are currently on 16.3.2.
Please keep in mind to announce this kind of changes and don't hide them in a "update some dependencies" message.

Is there any chance to got this chrome v74 fix in an 2.1.1 Version?

⁣Regards,
Waize

**Comment by maximilianoforlenza** [comment]
No, should fork the project, back to version 2.1.1 fix and use the forked version.

**Comment by maximilianoforlenza** [comment]
If it's working https://codesandbox.io/s/7jkkj5vkn1 I close this issue @Waize
