### ISSUE TITLE
Error when importing Treebeard into project

### ISSUE THREAD

**Issue by fengshuo** [storybooks/react-treebeard#62]
Hi Alex,  

I got this error when I added Treebeard into the project:  
`Uncaught TypeError: Super expression must either be null or a function, not undefined`.   
This exception is thrown by radium/lib/components/style.js:  
```
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
```

In package.json file, Treebeard is using `"radium": "^0.18.0"`, however It seems that Radium is relying some new features added in React `15.3` (see [here](https://github.com/FormidableLabs/radium/issues/884)), but we are using React `0.14.8`.  

Any suggestions to integrate Treebeard in a React `0.14` based project? Do you think relying on an earlier version of Radium is possible since the `React.PureComponent` was[ just added last month](https://github.com/FormidableLabs/radium/blob/master/CHANGELOG.md)?Thanks.

**Comment by fengshuo** [comment]
I switched to an earlier version of treebeard(`1.1.2`) which uses radium 0.16.x, it seems to be working okay now. But I don't think the example in the README.md is working.

**Comment by MichaelDeBoey** [comment]
@fengshuo I don't think this one's still present in [`v2.0.2`](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.2)?

**Comment by fengshuo** [comment]
@MichaelDeBoey I haven't tried the new version yet, the older versions worked for me.

**Comment by MichaelDeBoey** [comment]
@fengshuo Could you please use the new version to verify?

**Comment by dinggaihua** [comment]
I switched to an earlier version of treebeard(1.1.2) which uses radium 0.16.x, it seems to be working okay now.

**Comment by MichaelDeBoey** [comment]
@dinggaihua I don't think this one's still present in [`v2.0.3`](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.3)?
