### ISSUE TITLE
Container is passed a copy of the 'node' instead of the original object

### ISSUE THREAD

**Issue by roonyh** [storybooks/react-treebeard#96]
We are using `Container` decorator so we can register a context-menu handler on it. But the node prop that is passed to it is a copy of the original node.

I found this happens because it is assigned to a new object [here](https://github.com/alexcurtis/react-treebeard/blob/832d81278b10ec88e0aecc32b4811aa42fe035cc/src/components/node.js#L86).

Is there any way we can access the original node object from inside the Container? Maybe as a different prop named say 'originalNode'?

**Comment by dperetti** [comment]
Same issue here as I wanted to use a custom immutable object instead of Object.

**Comment by roonyh** [comment]
Sent #98 to pass the actual node object as another prop named originalNode
